# Generated by Django 4.2.20 on 2025-05-07 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lims', '0078_auto_20241209_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('automounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.container')),
                ('beamline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.beamline')),
                ('selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected', to='lims.container')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
