# Generated by Django 4.2.20 on 2025-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
