# Generated by Django 4.2.20 on 2025-05-08 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_config_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='pending',
        ),
        migrations.AddField(
            model_name='config',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
