# Generated by Django 4.2.20 on 2025-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0003_remove_config_pending_config_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='loaded',
            field=models.JSONField(default=dict),
        ),
    ]
