# Generated by Django 3.0.2 on 2020-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamlineproject',
            name='expiration',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='beamlineproject',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Project ID'),
        ),
        migrations.AlterUniqueTogether(
            name='beamlineproject',
            unique_together={('number',)},
        ),
    ]
