# Generated by Django 3.0.2 on 2020-02-11 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200211_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamtime',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beamtime',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 17, 4, 17, 747386, tzinfo=utc), verbose_name='End'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beamtime',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beamtime', to='schedule.VisitType'),
        ),
        migrations.AlterField(
            model_name='beamtime',
            name='start',
            field=models.DateTimeField(verbose_name='Start'),
        ),
    ]
