# Generated by Django 3.0.2 on 2020-02-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200211_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitType',
            new_name='AccessType',
        ),
    ]
