# Generated by Django 3.0.2 on 2020-02-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200211_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamtimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beamtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_type', to='schedule.Beamtime')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='schedule.AccessType')),
            ],
        ),
        migrations.AlterField(
            model_name='beamtime',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beamtimes', to='schedule.BeamtimeType'),
        ),
    ]
