# Generated by Django 3.0.2 on 2020-02-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200211_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamtime',
            name='kind',
        ),
        migrations.AlterField(
            model_name='beamtimetype',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beamtime', to='schedule.AccessType'),
        ),
    ]
