# Generated by Django 3.0.2 on 2020-02-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200211_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamtimetype',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_type', to='schedule.AccessType'),
        ),
    ]
