# Generated by Django 3.0.2 on 2020-02-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20200213_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamtime',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamtime', to='schedule.BeamlineProject'),
        ),
    ]
