# Generated by Django 3.0.2 on 2020-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20200213_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('scope', models.IntegerField(choices=[(0, 'Facility'), (1, 'Beamline')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
