# Generated by Django 3.0.2 on 2020-02-28 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0050_data_frames_per_file'),
        ('schedule', '0013_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='beamline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='downtime', to='lims.Beamline'),
            preserve_default=False,
        ),
    ]
