# Generated by Django 3.0.2 on 2020-02-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_downtime_beamline'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
