# Generated by Django 3.0.2 on 2020-03-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_downtime_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Email Type')),
                ('subject', models.CharField(max_length=100, verbose_name='Email Subject')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Email Subject')),
                ('body', models.TextField(blank=True)),
                ('beamtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schedule.Beamtime')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schedule.EmailType')),
            ],
        ),
    ]
