# Generated by Django 3.0.2 on 2020-03-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_emailnotification_emailtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beamlineproject',
            old_name='project',
            new_name='account',
        ),
    ]
