# Generated by Django 3.0.2 on 2020-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20200302_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstype',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accesstype',
            name='email_subject',
            field=models.CharField(default='hello', max_length=100, verbose_name='Email Subject'),
            preserve_default=False,
        ),
    ]
