# Generated by Django 3.0.2 on 2020-03-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20200302_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamtime',
            name='access',
        ),
        migrations.AddField(
            model_name='beamtime',
            name='access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.AccessType'),
        ),
    ]
