# Generated by Django 3.0.2 on 2020-03-02 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20200302_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Send Time'),
            preserve_default=False,
        ),
    ]
