# Generated by Django 3.0.2 on 2020-03-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20200302_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamlineproject',
            name='title',
        ),
    ]
