# Generated by Django 3.0.2 on 2020-03-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_remove_beamlineproject_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamtime',
            name='notify',
        ),
        migrations.RemoveField(
            model_name='beamtime',
            name='sent',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
