# Generated by Django 3.0.2 on 2020-03-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20200302_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='body',
            new_name='email_body',
        ),
        migrations.RenameField(
            model_name='emailnotification',
            old_name='subject',
            new_name='email_subject',
        ),
    ]
