# Generated by Django 3.0.2 on 2020-03-04 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0025_auto_20200302_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamtime',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamtime', to=settings.AUTH_USER_MODEL),
        ),
    ]
