# Generated by Django 3.0.2 on 2020-03-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_auto_20200304_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeamlineProject',
        ),
    ]
