version: '2'
services:
  database:
    image: postgres-bkup:latest
    volumes:
      - ./database:/var/lib/postgresql/data:Z
      - ./database-init:/docker-entrypoint-initdb.d:Z
      - ./database-backups:/backups:Z
    environment:
      POSTGRES_PASSWORD: '*****secret*****'
      DATABASE_USER: postgres
      BACKUP_DATABASE_USER: postgres

    restart: always

  files:
    image: mxlive-dataproxy:latest
    environment:
      SERVER_NAME: files.local
    restart: always
    volumes:
    - ./files/local:/dataserver/local:Z
    - /home:/users:ro
    - ./files/archive:/archive:ro
    - ./files/cache:/cache:Z

  cache:
    image: memcached
    restart: always

  app:
    image: mxlive:latest
    hostname: mxlive.example.com
    environment:
      SERVER_NAME: mxlive.example.com
    volumes:
      - ./app/local:/mxlive/local:Z
      - ./app/certs:/etc/letsencrypt:Z
    ports:
      - "443:443"
    restart: always