database:
  image: opi2051-002:5000/postgres:backup
  volumes:
    - ./database:/var/lib/postgresql/data:Z
    - ./db-init:/docker-entrypoint-initdb.d:Z
    - ./backups:/backups:Z
  environment:
    POSTGRES_PASSWORD: nievoo8Oe3HuYoh1ahkiemei
    DATABASE_USER: postgres
    BACKUP_DATABASE_USER: postgres
  ports:
    - 5432:5432
  restart: always

mail:
  image: opi2051-002:5000/mail-server
  restart: always
  environment:
    maildomain:  mail.cmcf
    smtp_user: system:MjMzYTY3NzcyYzc0ZWE3YjVjOTcyYjFl

ldap:
  image: docker.io/minkwe/389ds:latest
  hostname: ldap.clsi.ca
  volumes:
    - ./ldap/data:/var/lib/dirsrv:Z
    - ./ldap/config:/etc/dirsrv:Z
    - ./ldap/logs:/var/log/dirsrv:Z
    - ./ldap/certs:/certs:Z
  environment:
    DIR_SUFFIX: "dc=cmcf,dc=cls"
    DIR_ADMIN_USERNAME: "cmcfadmin"
    DIR_MANAGER_PASSWORD: "appl4Str"
    DIR_ADMIN_UID: "2000"
    DIR_USERS_HOME: "/users"
  ports:
    - "389:389"
    - "636:636"
  restart: always

dataserver:
  image: opi2051-002:5000/dataserver:latest
  restart: always
  volumes:
    - ./dataserver:/dataserver/local:Z
    - /users:/users:ro
    - /archive:/archive:ro
  links:
    - database:data-db

mxlive:
  image: opi2051-002:5000/mxlive:mxlive-refresh
  environment:
    SERVER_NAME: cmcf.local
  volumes:
    - ./mxlive:/mxlive/local:Z
    - ./certbot:/etc/letsencrypt:Z
    - /users:/users:ro
  ports:
    - 443:443
  links:
    - database:mxlive-db
    - ldap:mxlive-ldap
    - mail:mxlive-mail
    - dataserver:mxlive-data
  restart: always

