database:
  image: mariadb
  hostname: sql.example.com
  volumes:
    - ./database:/var/lib/mysql:Z
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: mxlive
  restart: always

mail:
  image: postfix
  restart: always
  environment:
    maildomain:  mail.mxlive
    smtp_user: system:secret

ldap:
  image: minkwe/389ds:latest
  hostname: ldap.example.com
  volumes:
    - ./ldap/data:/var/lib/dirsrv:Z
    - ./ldap/config:/etc/dirsrv:Z
    - ./ldap/logs:/var/log/dirsrv:Z
    - ./ldap/certs:/certs:Z
  environment:
    DIR_SUFFIX: "dc=example,dc=com"
    DIR_ADMIN_USERNAME: "admin"
    DIR_MANAGER_PASSWORD: "secret"
    DIR_ADMIN_UID: "10000"
    DIR_USERS_HOME: "/users"
  ports:
    - "389:389"
    - "636:636"
  restart: always

app:
  image: mxlive:latest
  hostname: mxlive.example.ca
  environment:
    SERVER_NAME: mxlive.example.ca
  volumes:
    - ./app:/mxlive/local:Z    
  ports:
    - 443:443
  links:
    - database:mxlive-db
    - ldap:mxlive-ldap
    - mail:mxlive-mail
  restart: always
      

