# Generated by Django 4.2.20 on 2025-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20250107_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='authors',
            new_name='author_names',
        ),
    ]
