# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20170718_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user',
            new_name='project',
        ),
    ]
