# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20170719_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='container_locations',
            field=models.ManyToManyField(null=True, to='lims.ContainerLocation'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='envelope',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='layout',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
