# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_auto_20170719_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerlocation',
            name='accepts',
            field=models.ManyToManyField(blank=True, related_name='locations', to='lims.ContainerType'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='container_locations',
            field=models.ManyToManyField(blank=True, to='lims.ContainerLocation'),
        ),
    ]
