# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_container_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='kind',
        ),
    ]
