# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_auto_20170719_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': 'Group'},
        ),
        migrations.AddField(
            model_name='experiment',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Shipment'),
        ),
    ]
