# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_experiment_sample_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='delta_angle',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Desired Delta Angle'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='multiplicity',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Desired Multiplicity'),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('project', 'name', 'shipment')]),
        ),
        migrations.AlterUniqueTogether(
            name='experiment',
            unique_together=set([('project', 'name', 'shipment')]),
        ),
    ]
