# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_auto_20170727_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='project',
        ),
        migrations.RemoveField(
            model_name='crystalform',
            name='project',
        ),
        migrations.RemoveField(
            model_name='crystalform',
            name='space_group',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='project',
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='cocktail',
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='crystal_form',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='delta_angle',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='i_sigma',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='multiplicity',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='r_meas',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='total_angle',
        ),
        migrations.RemoveField(
            model_name='result',
            name='strategy',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample_count',
            field=models.PositiveIntegerField(default=1, verbose_name=b'Number of Samples'),
        ),
        migrations.DeleteModel(
            name='Cocktail',
        ),
        migrations.DeleteModel(
            name='CrystalForm',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
