# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_auto_20170803_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiment',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Crystal',
            new_name='Sample',
        ),
    ]
