# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0016_auto_20170803_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='dewar',
        ),
    ]
