# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0017_remove_container_dewar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='staff_priority',
        ),
        migrations.RemoveField(
            model_name='group',
            name='staff_priority',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='staff_priority',
        ),
    ]
