# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0020_auto_20170803_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group'},
        ),
        migrations.AlterField(
            model_name='group',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.Shipment'),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([]),
        ),
    ]
