# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0021_auto_20170811_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('project', 'name', 'shipment')]),
        ),
    ]
