# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0022_auto_20170811_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='screen_status',
        ),
        migrations.AlterField(
            model_name='sample',
            name='collect_status',
            field=models.BooleanField(default=False),
        ),
    ]
