# Generated by Django 2.2.5 on 2019-11-10 00:24

from django.db import migrations, models


def save_loc_name(apps, schema_editor):
    """
    Save Locations from layout into Location Object
    """
    Sample = apps.get_model('lims', 'Sample')

    db_alias = schema_editor.connection.alias
    Sample.objects.filter(container__isnull=True).delete()
    Sample.objects.filter(location__isnull=True).delete()
    Sample.objects.using(db_alias).update(loc_name=models.F('location'))
    for s in Sample.objects.all():
        loc = s.container.kind.locations.get(name=s.location)
        s.location = loc.pk
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0023_sample_loc_name'),
    ]

    operations = [
        migrations.RunPython(save_loc_name),
    ]
