# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0023_auto_20170814_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lims.Container'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='kind',
            field=models.IntegerField(choices=[(0, b'Cassette'), (1, b'Uni-Puck'), (2, b'Cane'), (3, b'Basket'), (4, b'Adaptor')], verbose_name=b'type'),
        ),
    ]
