# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0025_container_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertype',
            name='kind',
        ),
    ]
