# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0026_remove_containertype_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dewar',
            name='project',
        ),
        migrations.RemoveField(
            model_name='dewar',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Dewar',
        ),
    ]
