# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0028_auto_20170818_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('project__name', 'kind', 'location')},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='status',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
