# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0030_analysisreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisreport',
            old_name='detail',
            new_name='details',
        ),
    ]
