# Generated by Django 3.0.1 on 2020-01-05 18:22

from django.db import migrations
from django.db.models import Q, F


def activity(apps, schema_editor):
    """
    Fix names and kinds of Data Analysis Reports
    """
    AnalysisReport = apps.get_model('lims', 'AnalysisReport')
    db_alias = schema_editor.connection.alias


    # XRD
    to_update = []
    for report in AnalysisReport.objects.using(db_alias).filter(kind__endswith="XRD Profile").annotate(data_name=F('data__name')):
        report.name = 'Azimuthal Integration of "{}"'.format(report.data_name)
        report.kind = 'XRD Analysis'
        to_update.append(report)

    AnalysisReport.objects.using(db_alias).bulk_update(to_update, fields=['name', 'kind'])

    # screening
    to_update = []
    for report in AnalysisReport.objects.using(db_alias).filter(kind__icontains="screening").annotate(data_name=F('data__name')):
        anom = 'Anomalous ' if 'Anomalous' in report.kind else ''
        report.name = '{}Screening of "{}"'.format(anom, report.data_name)
        report.kind = 'MX Screening'
        to_update.append(report)

    AnalysisReport.objects.using(db_alias).bulk_update(to_update, fields=['name', 'kind'])

    # data processing
    to_update = []
    for report in AnalysisReport.objects.using(db_alias).filter(Q(kind__icontains="Analysis")|Q(kind__icontains="Processing")).annotate(data_name=F('data__name')):
        if 'Anomalous' in report.kind:
            report.name = 'Anomalous Data Processing of "{}"'.format(report.data_name)
            report.kind = 'MX Anomalous Analysis'
        elif 'Merged' in report.kind:
            report.name = 'Merging of "{}"'.format(report.data_name)
            report.kind = 'MX Merging'
        else:
            report.name = 'Native Processing of "{}"'.format(report.data_name)
            report.kind = 'MX Native Analysis'
        to_update.append(report)

    AnalysisReport.objects.using(db_alias).bulk_update(to_update, fields=['name', 'kind'])

    # mosgo
    to_update = []
    mosgo_screening = Q(kind__icontains="Mosgo Stategy") | Q(kind__icontains="MOSFLM")
    for report in AnalysisReport.objects.using(db_alias).filter(mosgo_screening):
        report.name = 'MOSFLM STRATEGY'
        report.kind = 'MOSFLM STRATEGY'
        to_update.append(report)

    AnalysisReport.objects.using(db_alias).bulk_update(to_update, fields=['name', 'kind'])

    # delete initial testing reports from 2011
    AnalysisReport.objects.using(db_alias).filter(kind="0").delete()




class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0045_auto_20191231_1956'),
    ]

    operations = [
        migrations.RunPython(activity)
    ]
