# Generated by Django 3.0.2 on 2020-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0052_auto_20200304_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
