# Generated by Django 3.2.25 on 2024-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0076_auto_20201020_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
