# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lims', '0023_auto_20170814_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'date modified')),
                ('comments', models.TextField(blank=True, null=True)),
                ('details', jsonfield.fields.JSONField(blank=True, default=[b'', b'', b'', b''], editable=False, null=True)),
                ('containers', models.ManyToManyField(blank=True, to='lims.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dewar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beamline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Beamline')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automounter', to='lims.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.IntegerField(blank=True, choices=[(0, b'News'), (1, b'How To')], null=True)),
                ('frame_type', models.IntegerField(blank=True, choices=[(0, b'iframe'), (1, b'flash'), (2, b'image'), (3, b'inline'), (4, b'link')], null=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(blank=True, upload_to=staff.models.get_storage_path, verbose_name='document')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'date modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Runlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Loaded'), (2, 'Unloaded'), (3, 'Incomplete'), (4, 'Completed'), (5, 'Closed')], default=0)),
                ('name', models.CharField(max_length=600)),
                ('priority', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'date modified')),
                ('comments', models.TextField(blank=True, null=True)),
                ('left', jsonfield.fields.JSONField(blank=True, null=True)),
                ('middle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('right', jsonfield.fields.JSONField(blank=True, null=True)),
                ('beamline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Beamline')),
                ('containers', models.ManyToManyField(blank=True, to='lims.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.GenericIPAddressField()),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name=b'date modified')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access List',
            },
        ),
    ]
