# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dewar',
            name='beamline',
        ),
        migrations.RemoveField(
            model_name='dewar',
            name='container',
        ),
        migrations.DeleteModel(
            name='Dewar',
        ),
    ]
