# Generated by Django 3.0.6 on 2020-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20200715_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteconnection',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
