"""
Django settings for mxlive project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from pathlib import Path

PROJECT_DIR = Path(__file__).parent
BASE_DIR = PROJECT_DIR.parent
LOCAL_DIR = BASE_DIR / 'local'

APP_NAME = 'MxLIVE'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f-=u8g58(4+$1&!pu%zx%&)5u+le%_#90*q7)n-6iifo5x2r0p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'allauth',
    'allauth.account',

    'memoize',
    'itemlist',
    'basiclive.core.lims',
    'basiclive.core.api',
    'basiclive.core.acl',
    'crispy_forms',
    'crispy_bootstrap4'
]
LIMS_USE_SCHEDULE = True
LIMS_USE_PUBLICATIONS = True
LIMS_USE_CRM = True
LIMS_USE_ACL = True
LIMS_LDAP_MANAGER = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'basiclive.auth.middleware.TrustedAccessMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'basiclive.auth.middleware.APIAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'mxlive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'basiclive.utils.context_processors.version_context_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'mxlive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': LOCAL_DIR / 'mxlive.db',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

AUTH_PROVIDERS = []
AUTH_USER_MODEL = 'lims.Project'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Regina'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
ASSETS_ROOT = PROJECT_DIR / "static" / "assets"     # Location of 3rd party asset files
STATICFILES_DIRS = [
    PROJECT_DIR / "static",
    ASSETS_ROOT,
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'local' / 'media'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# LDAP Server Settings
LDAP_BASE_DN = 'dc=demo1,dc=freeipa,dc=org'
LDAP_SERVER_URI = 'ipa.demo1.freeipa.org'
LDAP_MANAGER_DN = 'cn=Directory Manager'
LDAP_MANAGER_SECRET = SECRET_KEY
LDAP_USER_TABLE = 'ou=People'
LDAP_USER_ROOT = '/home'
LDAP_GROUP_TABLE = 'ou=Groups'
LDAP_USER_SHELL ='/bin/bash'
LDAP_SEND_EMAILS = False
LDAP_ADMIN_UIDS = [2000]

# LDAP Authentication Settings
LDAP_AUTH_URL = "ldap://{}:389".format(LDAP_SERVER_URI)
LDAP_AUTH_SEARCH_BASE = "{}{}".format(LDAP_USER_TABLE, LDAP_BASE_DN)
LDAP_AUTH_OBJECT_CLASS = "posixAccount"
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_USE_TLS = True

# Trusted clients for internal network
TRUSTED_IPS = ['127.0.0.1/32']
TRUSTED_PROXIES = 1
TRUSTED_URLS = ['^/json', '^/api']

# Shift parameters
HOURS_PER_SHIFT = 8

# Downloads
RESTRICT_DOWNLOADS = False
DOWNLOAD_PROXY_URL = "http://mxlive-data/download"

CRISPY_TEMPLATE_PACK = 'bootstrap4'

try:
    from local.settings import *
    print('Importing local settings from {}'.format(LOCAL_DIR / 'settings.py'))
except ImportError as err:
    print('Error importing local settings: {}'.format(err))

if LIMS_USE_SCHEDULE:
    INSTALLED_APPS.extend(['basiclive.core.schedule', 'colorfield'])

if LIMS_USE_PUBLICATIONS:
    INSTALLED_APPS.extend(['basiclive.core.publications'])

if LIMS_USE_CRM:
    INSTALLED_APPS.extend(['basiclive.core.crm'])

if AUTH_PROVIDERS:
    INSTALLED_APPS.extend(['allauth.socialaccount'])
    for provider in AUTH_PROVIDERS:
        if provider == 'ldap':
            AUTHENTICATION_BACKENDS[0] = 'django_python3_ldap.auth.LDAPBackend'
        elif provider == 'cas':
            AUTHENTICATION_BACKENDS[0] = 'django_cas_ng.backends.CASBackend'
        else:
            INSTALLED_APPS.append(f'allauth.socialaccount.providers.{provider}')
