# Generated by Django 4.2.18 on 2025-02-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=150)),
                ('fields', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filters', models.JSONField(default=dict)),
                ('group_by', models.JSONField(default=list)),
                ('order_fields', models.JSONField(default=list)),
                ('group_fields', models.JSONField(default=list)),
                ('filter_fields', models.JSONField(default=dict)),
                ('limit', models.IntegerField(null=True)),
                ('order_by', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('kind', models.CharField(choices=[('annotation', 'Annotation'), ('aggregation', 'Aggregation')], default='annotation', max_length=50)),
                ('label', models.CharField(max_length=100, null=True)),
                ('default', models.JSONField(null=True)),
                ('expression', models.JSONField(null=True)),
                ('precision', models.IntegerField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.datamodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reporter.datasource')),
            ],
            options={
                'unique_together': {('name', 'source', 'model')},
            },
        ),
    ]
