# Generated by Django 4.2.18 on 2025-02-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='model',
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
