# Generated by Django 4.2.18 on 2025-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_remove_datamodel_model_alter_datamodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='expression',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='filter_fields',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='filters',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='group_by',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='group_fields',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='order_by',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='order_fields',
            field=models.JSONField(default=list, null=True),
        ),
    ]
