# Generated by Django 4.2.18 on 2025-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_alter_datafield_expression_alter_datamodel_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='filter_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='group_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='group_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='order_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='order_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
