# Generated by Django 4.2.18 on 2025-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_alter_datasource_filter_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='default',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='expression',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='precision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
