# Generated by Django 4.2.18 on 2025-02-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_alter_datafield_default_alter_datafield_expression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('style', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('style', models.CharField(blank=True, default='', max_length=100)),
                ('kind', models.CharField(choices=[('bars', 'Bar Chart'), ('table', 'Table'), ('list', 'List'), ('plot', 'XY Plot'), ('pie', 'Pie Chart'), ('histogram', 'Histogram'), ('timeline', 'Timeline')], default='table', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reporter.report')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.datasource')),
            ],
        ),
    ]
