# Generated by Django 4.2.18 on 2025-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_report_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='junk', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
