# Generated by Django 4.2.18 on 2025-02-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_datafield_created_datafield_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['report', 'position'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='order',
            new_name='position',
        ),
    ]
