# Generated by Django 4.2.18 on 2025-02-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_alter_entry_options_rename_order_entry_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafield',
            options={'ordering': ['source', 'position']},
        ),
        migrations.AddField(
            model_name='datafield',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reporter.datasource'),
        ),
    ]
