# Generated by Django 4.2.18 on 2025-02-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0010_alter_datafield_options_datafield_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafield',
            options={'ordering': ['source', 'position', 'pk']},
        ),
        migrations.AddField(
            model_name='datafield',
            name='grouped',
            field=models.BooleanField(default=False),
        ),
    ]
