# Generated by Django 4.2.18 on 2025-02-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_alter_datafield_options_datafield_grouped'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='filtered',
            field=models.BooleanField(default=False),
        ),
    ]
