# Generated by Django 4.2.18 on 2025-02-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0012_datafield_filtered'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='descending',
            field=models.BooleanField(default=False),
        ),
    ]
