# Generated by Django 4.2.18 on 2025-02-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0013_datasource_descending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafield',
            old_name='filtered',
            new_name='filterable',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='group_by',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='order_by',
        ),
    ]
