# Generated by Django 4.2.18 on 2025-02-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0014_rename_filtered_datafield_filterable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='filter_fields',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='group_fields',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='order_fields',
        ),
    ]
