# Generated by Django 4.2.18 on 2025-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0015_remove_datasource_filter_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
