# Generated by Django 4.2.18 on 2025-02-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_datafield_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='descending',
        ),
    ]
