# Generated by Django 4.2.18 on 2025-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0017_remove_datasource_descending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
