# Generated by Django 4.2.18 on 2025-02-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0018_alter_datamodel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='distinct',
            field=models.BooleanField(default=False),
        ),
    ]
