# Generated by Django 4.2.18 on 2025-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0019_datafield_distinct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='distinct',
        ),
        migrations.AlterField(
            model_name='entry',
            name='style',
            field=models.CharField(blank=True, choices=[('col-md-3', 'One Quarter'), ('col-md-4', 'One Third'), ('col-md-6', 'Half'), ('col-md-8', 'Two Thirds'), ('col-md-9', 'Three Quarters'), ('col-md-12', 'Full Width')], default='col-md-12', max_length=100, verbose_name='Width'),
        ),
    ]
