# Generated by Django 4.2.18 on 2025-02-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0020_remove_datafield_distinct_alter_entry_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='kind',
            field=models.CharField(choices=[('bars', 'Bar Chart'), ('table', 'Table'), ('list', 'List'), ('plot', 'XY Plot'), ('pie', 'Pie Chart'), ('histogram', 'Histogram'), ('timeline', 'Timeline'), ('text', 'Rich Text')], default='table', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reporter.datasource'),
        ),
    ]
