# Generated by Django 4.2.20 on 2025-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0021_alter_entry_kind_alter_entry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='group_by',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Group Fields'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='kind',
            field=models.CharField(choices=[('bars', 'Bar Chart'), ('table', 'Table'), ('list', 'List'), ('plot', 'XY Plot'), ('pie', 'Pie Chart'), ('histogram', 'Histogram'), ('timeline', 'Timeline'), ('text', 'Rich Text')], default='table', max_length=50, verbose_name='Type'),
        ),
    ]
