# Generated by Django 4.2.20 on 2025-03-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reporter', '0022_datasource_group_by_alter_entry_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='reporter.datasource'),
            preserve_default=False,
        ),
    ]
