# Generated by Django 4.2.20 on 2025-03-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0023_datamodel_model_datamodel_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='fields',
        ),
        migrations.AlterField(
            model_name='datafield',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reporter.datamodel'),
        ),
    ]
