# Generated by Django 4.2.20 on 2025-03-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0024_remove_datamodel_fields_alter_datafield_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='filterable',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='grouped',
        ),
        migrations.AlterField(
            model_name='datafield',
            name='kind',
            field=models.CharField(choices=[('annotation', 'Annotation'), ('aggregation', 'Aggregation')], default='aggregation', max_length=50),
        ),
    ]
