# Generated by Django 4.2.20 on 2025-03-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0025_remove_datafield_filterable_remove_datafield_grouped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='kind',
        ),
    ]
