# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 16:03
from __future__ import unicode_literals

import apikey.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=60)),
                ('client_email', models.EmailField(blank=True, max_length=75, null=True)),
                ('allowed_hosts', apikey.fields.IPNetworkField()),
                ('allowed_methods', models.CharField(blank=True, default=b'', max_length=255)),
                ('key', models.CharField(db_index=True, editable=False, max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name=b'date modified')),
            ],
            options={
                'verbose_name': 'API Key',
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=60)),
                ('host', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.APIKey')),
            ],
            options={
                'verbose_name': 'API Key Usage',
            },
        ),
    ]
